//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;

namespace ezweather.services.Resources
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class condition
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class icon
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class xml_api_reply
    {

        private xml_api_replyWeather[] weatherField;

        private string versionField;

        /// <remarks/>
        [XmlElement("weather", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeather[] weather
        {
            get
            {
                return this.weatherField;
            }
            set
            {
                this.weatherField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeather
    {

        private xml_api_replyWeatherForecast_information[] forecast_informationField;

        private xml_api_replyWeatherCurrent_conditions[] current_conditionsField;

        private xml_api_replyWeatherForecast_conditions[] forecast_conditionsField;

        private string module_idField;

        private string tab_idField;

        private string mobile_rowField;

        private string mobile_zippedField;

        private string rowField;

        private string sectionField;

        /// <remarks/>
        [XmlElement("forecast_information", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_information[] forecast_information
        {
            get
            {
                return this.forecast_informationField;
            }
            set
            {
                this.forecast_informationField = value;
            }
        }

        /// <remarks/>
        [XmlElement("current_conditions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherCurrent_conditions[] current_conditions
        {
            get
            {
                return this.current_conditionsField;
            }
            set
            {
                this.current_conditionsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("forecast_conditions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_conditions[] forecast_conditions
        {
            get
            {
                return this.forecast_conditionsField;
            }
            set
            {
                this.forecast_conditionsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string module_id
        {
            get
            {
                return this.module_idField;
            }
            set
            {
                this.module_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string tab_id
        {
            get
            {
                return this.tab_idField;
            }
            set
            {
                this.tab_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string mobile_row
        {
            get
            {
                return this.mobile_rowField;
            }
            set
            {
                this.mobile_rowField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string mobile_zipped
        {
            get
            {
                return this.mobile_zippedField;
            }
            set
            {
                this.mobile_zippedField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_information
    {

        private xml_api_replyWeatherForecast_informationCity[] cityField;

        private xml_api_replyWeatherForecast_informationPostal_code[] postal_codeField;

        private xml_api_replyWeatherForecast_informationLatitude_e6[] latitude_e6Field;

        private xml_api_replyWeatherForecast_informationLongitude_e6[] longitude_e6Field;

        private xml_api_replyWeatherForecast_informationForecast_date[] forecast_dateField;

        private xml_api_replyWeatherForecast_informationCurrent_date_time[] current_date_timeField;

        private xml_api_replyWeatherForecast_informationUnit_system[] unit_systemField;

        /// <remarks/>
        [XmlElement("city", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationCity[] city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [XmlElement("postal_code", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationPostal_code[] postal_code
        {
            get
            {
                return this.postal_codeField;
            }
            set
            {
                this.postal_codeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("latitude_e6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationLatitude_e6[] latitude_e6
        {
            get
            {
                return this.latitude_e6Field;
            }
            set
            {
                this.latitude_e6Field = value;
            }
        }

        /// <remarks/>
        [XmlElement("longitude_e6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationLongitude_e6[] longitude_e6
        {
            get
            {
                return this.longitude_e6Field;
            }
            set
            {
                this.longitude_e6Field = value;
            }
        }

        /// <remarks/>
        [XmlElement("forecast_date", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationForecast_date[] forecast_date
        {
            get
            {
                return this.forecast_dateField;
            }
            set
            {
                this.forecast_dateField = value;
            }
        }

        /// <remarks/>
        [XmlElement("current_date_time", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationCurrent_date_time[] current_date_time
        {
            get
            {
                return this.current_date_timeField;
            }
            set
            {
                this.current_date_timeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("unit_system", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_informationUnit_system[] unit_system
        {
            get
            {
                return this.unit_systemField;
            }
            set
            {
                this.unit_systemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationCity
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationPostal_code
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationLatitude_e6
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationLongitude_e6
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationForecast_date
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationCurrent_date_time
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_informationUnit_system
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherCurrent_conditions
    {

        private condition[] conditionField;

        private xml_api_replyWeatherCurrent_conditionsTemp_f[] temp_fField;

        private xml_api_replyWeatherCurrent_conditionsTemp_c[] temp_cField;

        private xml_api_replyWeatherCurrent_conditionsHumidity[] humidityField;

        private icon[] iconField;

        private xml_api_replyWeatherCurrent_conditionsWind_condition[] wind_conditionField;

        /// <remarks/>
        [XmlElement("condition")]
        public condition[] condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [XmlElement("temp_f", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherCurrent_conditionsTemp_f[] temp_f
        {
            get
            {
                return this.temp_fField;
            }
            set
            {
                this.temp_fField = value;
            }
        }

        /// <remarks/>
        [XmlElement("temp_c", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherCurrent_conditionsTemp_c[] temp_c
        {
            get
            {
                return this.temp_cField;
            }
            set
            {
                this.temp_cField = value;
            }
        }

        /// <remarks/>
        [XmlElement("humidity", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherCurrent_conditionsHumidity[] humidity
        {
            get
            {
                return this.humidityField;
            }
            set
            {
                this.humidityField = value;
            }
        }

        /// <remarks/>
        [XmlElement("icon")]
        public icon[] icon
        {
            get
            {
                return this.iconField;
            }
            set
            {
                this.iconField = value;
            }
        }

        /// <remarks/>
        [XmlElement("wind_condition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherCurrent_conditionsWind_condition[] wind_condition
        {
            get
            {
                return this.wind_conditionField;
            }
            set
            {
                this.wind_conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherCurrent_conditionsTemp_f
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherCurrent_conditionsTemp_c
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherCurrent_conditionsHumidity
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherCurrent_conditionsWind_condition
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_conditions
    {

        private xml_api_replyWeatherForecast_conditionsDay_of_week[] day_of_weekField;

        private xml_api_replyWeatherForecast_conditionsLow[] lowField;

        private xml_api_replyWeatherForecast_conditionsHigh[] highField;

        private icon[] iconField;

        private condition[] conditionField;

        /// <remarks/>
        [XmlElement("day_of_week", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_conditionsDay_of_week[] day_of_week
        {
            get
            {
                return this.day_of_weekField;
            }
            set
            {
                this.day_of_weekField = value;
            }
        }

        /// <remarks/>
        [XmlElement("low", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_conditionsLow[] low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [XmlElement("high", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public xml_api_replyWeatherForecast_conditionsHigh[] high
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }

        /// <remarks/>
        [XmlElement("icon")]
        public icon[] icon
        {
            get
            {
                return this.iconField;
            }
            set
            {
                this.iconField = value;
            }
        }

        /// <remarks/>
        [XmlElement("condition")]
        public condition[] condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_conditionsDay_of_week
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_conditionsLow
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(AnonymousType = true)]
    public partial class xml_api_replyWeatherForecast_conditionsHigh
    {

        private string dataField;

        /// <remarks/>
        [XmlAttribute()]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
}